env:
  browser: true
  commonjs: true
  es6: true
  jest: true
  node: false
  worker: true
extends:
  - eslint:recommended
  - plugin:security/recommended
  - plugin:promise/recommended
  - airbnb
globals:
  Array: true
  Date: true
  JSON: true
  Map: true
  Math: true
  Number: true
  Object: true
  Promise: true
  Set: true
  URL: true
  document: true
  module: true
  navigator: true
  process: true
  window: true
parserOptions:
  codeFrame: false
  ecmaFeatures:
    spread: true
    impliedStrict: true
    jsx: true
  ecmaVersion: 10
  sourceType: module
plugins:
  - optimize-regex
  - filenames
  - import
  - promise
  - compat
  - security
root: true
rules:
  react/prop-types: 0
  react/jsx-filename-extension: 0
  react/no-array-index-key: 0
  max-len: 0
  class-methods-use-this: 0
  comma-dangle: 0
  object-curly-newline: 0
  no-mixed-operators: 0
  no-await-in-loop: 0
  react/jsx-one-expression-per-line: 0
  no-confusing-arrow: 0
  react/destructuring-assignment: 0
